const apdDatabase = [
    { id: "Signal 1", type: "Signal", desc: "Abandon Auto", layman: "Car left empty on the side of the road or blocking lanes", sentence: "We have an unmonitored block on North Ave matching a Signal 1 log." },
    { id: "Signal 1R", type: "Signal", desc: "Recovered Auto", sentence: "Direct units to check the back lot for a verified Signal 1R tracking record.", layman: "A stolen car that was found and recovered by police officers" },
    { id: "Signal 2S", type: "Signal", desc: "Silent Alarm", sentence: "Tripped monitoring relays at the jeweler storefront report a Signal 2S line.", layman: "A silent security alarm tripped at a store without any noise" },
    { id: "Signal 2A", type: "Signal", desc: "Audible Alarm", sentence: "Zone 5, respond to a loud Signal 2A sound cycle at the depot warehouse.", layman: "A loud security alarm making lots of noise at a property storefront" },
    { id: "Signal 3", type: "Signal", desc: "Fire Alarm", sentence: "Clear the frequency, routing support units for an active Signal 3 junction.", layman: "A fire alarm building indicator has gone off calling for help" },
    { id: "Signal 4", type: "Signal", desc: "Carbon Monoxide", sentence: "Hazmat parameters initiated on scene following an environment Signal 4 breach.", layman: "Dangerous, toxic gas detected leaking inside a residence framework" },
    { id: "Signal 6B", type: "Signal", desc: "Burglary (business)", sentence: "Commercial security doors broken on scene, log as a Signal 6B dispatch.", layman: "Someone broke into a locked commercial store or business building" },
    { id: "Signal 6R", type: "Signal", desc: "Burglary (residence)", sentence: "En route to a residential perimeter check regarding a suspicious Signal 6R entry.", layman: "Someone broke into a private home or residential property location" },
    { id: "Signal 7", type: "Signal", desc: "Criminal Trespass", sentence: "Property owner wants an individual removed for a verified Signal 7.", layman: "An unwanted person refusing to leave private property" },
    { id: "Signal 10", type: "Signal", desc: "Wash Down", sentence: "Send sanitation and engine support crews to handle a roadside Signal 10 clear.", layman: "Cleaning up fuel or hazardous fluid spills from a roadway crash site" },
    { id: "Signal 15", type: "Signal", desc: "Check Welfare", sentence: "Conduct a physical Signal 15 audit on an elderly individual missing check-ins.", layman: "Go check on a person's health and physical safety because no one has heard from them" },
    { id: "Signal 16", type: "Signal", desc: "Emergency Message", sentence: "Standby for a high-priority Signal 16 broadcast direct from Command.", layman: "A critical emergency message delivered directly to working sector units" },
    { id: "Signal 17", type: "Signal", desc: "Lockout", sentence: "Vehicle running with minor child inside, units assist on a priority Signal 17.", layman: "Keys locked inside a running vehicle or home causing immediate safety issues" },
    { id: "Signal 18", type: "Signal", desc: "Tree Down", sentence: "Peachtree road blocked completely by power lines and a Signal 18 incident.", layman: "A fallen tree trunk blocking a public street partition or sidewalk path" },
    { id: "Signal 19", type: "Signal", desc: "Water Problem", sentence: "Main valve rupture causing structural shifts, tag as an absolute Signal 19.", layman: "A broken city water pipe line flooding properties or public streets" },
    { id: "Signal 20A", type: "Signal", desc: "Cont. Disease-HIV", sentence: "Medical dispatch updates unit parameters to observe Signal 20A guidelines.", layman: "Warning flag to use high caution due to dynamic fluid infectious disease profile" },
    { id: "Signal 20H", type: "Signal", desc: "Cont. Disease-Hep", sentence: "Exercise contact clean mechanics under specialized Signal 20H conditions.", layman: "Warning flag indicating hepatitis exposure risk parameters on scene" },
    { id: "Signal 20T", type: "Signal", desc: "Cont. Disease-TB", sentence: "Airborn containment protection systems verified for a known Signal 20T.", layman: "Warning flag indicating airborne tuberculosis bacteria safety risk on assignment" },
    { id: "Signal 21", type: "Signal", desc: "Kidnapping", sentence: "Initiate interstate roadblocks immediately to isolate a suspect Signal 21 vehicle.", layman: "Abducting a citizen by physical force against their legal rights" },
    { id: "Signal 22", type: "Signal", desc: "Against Dept. Policy", sentence: "Actions monitored on channel 2 are flagged under standard Signal 22 review.", layman: "An action that strictly breaks official police department employee guidelines" },
    { id: "Signal 23", type: "Signal", desc: "Disorderly Children", sentence: "Large juvenile group causing business terminal disruption, clear a Signal 23.", layman: "A rowdy group of kids or juveniles causing disruptions in public spaces" },
    { id: "Signal 24", type: "Signal", desc: "Demented Person", sentence: "Individual running into active traffic flows, handle under a safe Signal 24 loop.", layman: "A person in mental crisis who may be acting erratically or dangerously" },
    { id: "Signal 25", type: "Signal", desc: "Shots Fired", sentence: "Ballistic acoustic locators detect three discharges, dispatch a Signal 25.", layman: "Gunfire bursts heard or reported inside a target coordinate area" },
    { id: "Signal 26", type: "Signal", desc: "Fireworks", sentence: "Holiday celebration crowds causing localized sound reports, verified Signal 26.", layman: "Exploding holiday fireworks creating loud noises in the sky area" },
    { id: "Signal 27", type: "Signal", desc: "Intoxicated Driver", sentence: "Vehicle swerving aggressively across highway partitions, call a Signal 27.", layman: "A drunk driver swerving all over the road lanes dangerously" }
];
const apdCodes = [
    { id: "Signal 28", type: "Signal", desc: "Intoxicated Person", sentence: "Unresponsive citizen resting on public stairs, handle under a routine Signal 28.", layman: "A heavily drunk person causing public problems or unable to walk safely" },
    { id: "Signal 29", type: "Signal", desc: "Fight in Progress", sentence: "Active physical combat involving multiple subjects, roll units Code 3 for a Signal 29.", layman: "People actively trading punches or beating each other up right now" },
    { id: "Signal 30", type: "Signal", desc: "Explosion (any type)", sentence: "Structural failure reports matching a violent shockwave, clear a Signal 30.", layman: "A powerful structural explosion blast that shattered nearby glass windows" },
    { id: "Signal 31", type: "Signal", desc: "Wire Down/Electrical Short", sentence: "Live components throwing active arcs onto sidewalks, mark a Signal 31.", layman: "A broken power line sparking on the ground or sidewalk trail" },
    { id: "Signal 32", type: "Signal", desc: "Open door/window", sentence: "Night patrol finds a commercial entry unlatched after hours, log a Signal 32.", layman: "An unlocked commercial door or open building window found at night" },
    { id: "Signal 33", type: "Signal", desc: "Structure Fire", sentence: "Engaging secondary defensive barriers alongside fire teams on a Signal 33.", layman: "An entire building or physical house structural facility caught on fire" },
    { id: "Signal 34", type: "Signal", desc: "Vehicle Fire", sentence: "Engine block fully engulfed on the expressway shoulder, dispatch a Signal 34.", layman: "A vehicle engine bay completely on fire blocking roadway lanes" },
    { id: "Signal 35", type: "Signal", desc: "Wood/grass Fire", sentence: "Brush fire threatening perimeter fences along transit paths, mark as a Signal 35.", layman: "Wild grass brush fire burning open territory areas uncontrollably" },
    { id: "Signal 36B", type: "Signal", desc: "Robbery In progress Business", sentence: "Panic buttons activated during a retail holdup, route all Code 3 for a Signal 36B.", layman: "An armed robber holding up a cashier inside a business store right now" },
    { id: "Signal 36P", type: "Signal", desc: "Robbery In progress Pedestrian", sentence: "Foot patrol intercepts a strongarm theft on the pathway, active Signal 36P.", layman: "An ongoing strongarm mugging of a citizen walking down a public path right now" },
    { id: "Signal 36R", type: "Signal", desc: "Robbery In progress Residential", sentence: "Home invaders inside the floor plan, tracking active Signal 36R elements.", layman: "Armed home invaders breaking in while residents are inside the house" },
    { id: "Signal 35C", type: "Signal", desc: "Carjacking (In progress)", layman: "Active vehicular theft by threat of force", sentence: "Zone 1 units roll Code 3 to an active tracking Signal 35C line." },
    { id: "Signal 37", type: "Signal", desc: "Illegal Parking", layman: "Vehicle blocking thoroughfares unlawfully", sentence: "Write a parking enforcement card for the Signal 37 left on the curb." },
    { id: "Signal 38", type: "Signal", desc: "Illegal Drugs/Alcohol", layman: "Unlawful narcotics or alcohol substances reported", sentence: "Found contraband inside the trunk, logging a clear Signal 38 block." },
    { id: "Signal 39", type: "Signal", desc: "Information to Officer", layman: "Updates or dispatch details sent to sector cars", sentence: "Standby for incoming tracking updates via a Signal 39 dispatch data node." },
    { id: "Signal 40", type: "Signal", desc: "Animal Call", layman: "Dangerous or stray animals roaming the area", sentence: "Stray vicious guard breed blocking sidewalk access routes, call a Signal 40." },
    { id: "Signal 41I", type: "Signal", desc: "Auto Accident/Injuries", layman: "Car crash where passengers are confirmed hurt", sentence: "Two cars collided with active driver injuries, route a Signal 41I." },
    { id: "Signal 41IT", type: "Signal", desc: "Auto Accident/Trapped", layman: "Car crash where passengers cannot break free from wreckage", sentence: "Extrication machinery required on the roadway to clear a severe Signal 41IT." },
    { id: "Signal 41F", type: "Signal", desc: "Auto Accident/Fire", layman: "Car crash that has ignited into active structural flames", sentence: "Impact split fuel infrastructure, engine area on fire, dispatch a Signal 41F." },
    { id: "Signal 41P", type: "Signal", desc: "Auto Accident/Police", layman: "Precinct patrol vehicle involved in an auto crash", sentence: "A precinct patrol car was clipped at an intersection, note a Signal 41P." },
    { id: "Signal 42B", type: "Signal", desc: "Commercial Burglary", layman: "Past break-in reported at a business storefront", sentence: "Past occurred safe break at a pharmacy vault, dispatch for a Signal 42B report." },
    { id: "Signal 42R", type: "Signal", desc: "Residential Burglary", layman: "Past break-in reported at a private residence home", sentence: "Homeowners returned to find electronic packages missing, file a Signal 42R." },
    { id: "Signal 43", type: "Signal", desc: "Hit and Run", layman: "Driver leaves the scene of a vehicle crash without stopping", sentence: "Fleeing vehicle left front bumper on scene, tracking a Signal 43 asset." },
    { id: "Signal 44B", type: "Signal", desc: "Business Robbery", layman: "Past robbery accomplished by force at a store location", sentence: "Past robbery occurred at a check cashing counter, log a guided Signal 44B." },
    { id: "Signal 44P", type: "Signal", desc: "Pedestrian Robbery", layman: "Past strongarm mugging of a walker on public pathways", sentence: "Victim approached on a transit path, wallet taken, register a Signal 44P." }
];
const apdDispositions = [
    { id: "Signal 44R", type: "Signal", desc: "Residential Robbery", sentence: "Armed suspect entered garage area to take belongings, report a Signal 44R.", layman: "Past armed robbery committed inside a citizen's home coordinates" },
    { id: "Signal 44C", type: "Signal", desc: "Carjacking", sentence: "Past occurred vehicle theft accomplished by dynamic threat, log a Signal 44C.", layman: "Past vehicle robbery completed through active weapons threats" },
    { id: "Signal 45", type: "Signal", desc: "Larceny", sentence: "Shoplifter walked past register banks without clearing payments, a Signal 45.", layman: "Theft of physical goods without breaking into a structure" },
    { id: "Signal 46", type: "Signal", desc: "Ped. Struck by Auto", sentence: "Pedestrian stepped into path of a vehicle, rolling medics to a Signal 46.", layman: "A person walking down the road was run over by a moving car" },
    { id: "Signal 47", type: "Signal", desc: "Person Injured", sentence: "Industrial construction equipment error led to a bad fall, log a Signal 47.", layman: "A citizen is physically injured from an accident on assignment" },
    { id: "Signal 48", type: "Signal", desc: "Person Dead", sentence: "Precinct coroner and detectives called out to confirm a Signal 48 case.", layman: "Deceased subject located on scene requiring investigations team processing" },
    { id: "Signal 49", type: "Signal", desc: "Rape", sentence: "Specialized investigators take over primary processing on a Signal 49.", layman: "Sexual assault incident report handled by dedicated special crimes teams" },
    { id: "Signal 50", type: "Signal", desc: "Person Shot", sentence: "Trauma assets requested immediate flight path cleared for a Signal 50.", layman: "A victim has been struck by active gunfire rounds on scene" },
    { id: "Signal 51", type: "Signal", desc: "Person Stabbed", sentence: "Altercation led to severe puncture lacerations, mark a Signal 51 dispatch.", layman: "A victim has been wounded by a knife puncture edge on assignment" },
    { id: "Signal 52", type: "Signal", desc: "Found Property", sentence: "Unclaimed dynamic luggage left at terminal desks processed under Signal 52.", layman: "Lost belongings recovered and logged into police evidence lockers safely" },
    { id: "Signal 53", type: "Signal", desc: "Suicide", sentence: "Crisis negotiations hand off to scene command blocks on a Signal 53.", layman: "Self-harm emergency call line handled by intervention lines" },
    { id: "Signal 54", type: "Signal", desc: "Suspicious Person", sentence: "Individual wearing dark gear inspecting backyard tree lines, code as Signal 54.", layman: "An unknown person acting weirdly or out of place around a property" },
    { id: "Signal 55", type: "Signal", desc: "911 Hang-up", sentence: "Emergency lines drop mid-transmission, sector cars verify a Signal 55 loop.", layman: "An emergency phone line cut off abruptly before info was checked" },
    { id: "Signal 56", type: "Signal", desc: "Missing Person", sentence: "Juvenile has failed to return from school grounds, activate a Signal 56 file.", layman: "An individual has vanished and their whereabouts are unknown" },
    { id: "Signal 57", type: "Signal", desc: "Noise Complaint", sentence: "Peachtree apartments report loud audio output past midnight, log a Signal 57.", layman: "Loud music or disruptive structural party noises past neighborhood limits" },
    { id: "Signal 58", type: "Signal", desc: "Domestic Disturbance", sentence: "Intense argument heard between residents across shared partitions, a Signal 58.", layman: "Intense argument heard between residents across shared partitions" },
    { id: "Signal 59", type: "Signal", desc: "Meet Officer", sentence: "Unit 301, make your way to the district station to Signal 59 with the Captain.", layman: "Instruction to physically meet up with an officer at a location" },
    { id: "Signal 60", type: "Signal", desc: "Molesting woman/child", sentence: "Priority investigative protocols initiated following a dynamic Signal 60 alert.", layman: "Abuse patterns intercepted requiring immediate physical separations" },
    { id: "Signal 60A", type: "Signal", desc: "Child Abuse", sentence: "Child services teams coordinate scene containment for a severe Signal 60A.", layman: "Physical child abuse reports tracked to a specific address point" },
    { id: "Signal 61", type: "Signal", desc: "Non Police Help Call", sentence: "Public assistance request outside standard operational mandates, a Signal 61.", layman: "A general citizen help request that does not involve active criminal law breaks" },
    { id: "Signal 62", type: "Signal", desc: "Switch Radio Channel", sentence: "Tactical teams command all sector tracking units to Signal 62 to Channel B.", layman: "Instruction for all sector radio terminals to change over to channel grids" },
    { id: "Signal 63", type: "Signal", desc: "OFFICER NEEDS HELP", sentence: "Emergency tones activate! Signal 63 broadcasted near the zone boundary!", layman: "Absolute highest priority alert indicating an officer is in danger" },
    { id: "Signal 64", type: "Signal", desc: "Person Soliciting Sex", sentence: "Plainclothes monitoring initiatives result in a localized Signal 64 sweep.", layman: "Illegal solicitation operations tracked by undercover street vice lines" },
    { id: "Signal 65", type: "Signal", desc: "Gambling", sentence: "Unlawful card tracking operations busted at an empty business, Signal 65.", layman: "Illegal betting or casino ring operations running behind closed doors" },
    { id: "Signal 66", type: "Signal", desc: "Peeping Tom", sentence: "Subject standing outside bedroom blinds caught on video, log a Signal 66.", layman: "An individual caught spying on citizens unlawfully through windows" }
];
const apdFinalSection = [
    { id: "Signal 67", type: "Signal", desc: "Hold Radio Traffic", sentence: "Emergency air protocol active, all standard stations hold for a Signal 67.", layman: "Radio silence order enforced on air for critical tactical alerts" },
    { id: "Signal 68", type: "Signal", desc: "Person Screaming", sentence: "Neighbors report loud structural vocal duress calls, verify a Signal 68 line.", layman: "Loud screams of distress heard coming from an address frame area" },
    { id: "Signal 69", type: "Signal", desc: "Person Armed", sentence: "Individual walking near train terminals carrying an unholstered rifle, Signal 69.", layman: "An individual walking around in public holding a visible weapon" },
    { id: "Signal 70", type: "Signal", desc: "Prowler", sentence: "Footsteps heard along side driveway areas, monitor for an active Signal 70.", layman: "A trespasser creeping around the exterior walls of a private home at night" },
    { id: "Signal 71", type: "Signal", desc: "Public Indecency", sentence: "Exhibitionist behavior tracking underway inside public parks, a Signal 71.", layman: "An individual exposes themselves indecently inside public view constraints" },
    { id: "Signal 72", type: "Signal", desc: "Traffic Stop", sentence: "Unit 305 out on a Signal 72 with a red motorcycle missing tag items.", layman: "An officer pulling over a vehicle driver for a traffic law violation" },
    { id: "Signal 72B", type: "Signal", desc: "Checkpoint", sentence: "Dynamic roadblock systems initialized for an evening security Signal 72B sweep.", layman: "A deliberate police roadblock setup to verify driver status items" },
    { id: "Signal 72P", type: "Signal", desc: "Pursuit", sentence: "High speed flight tracking initiated on a felony car, signal a Signal 72P.", layman: "High speed chase of a fleeing vehicle happening on road systems" },
    { id: "Signal 73", type: "Signal", desc: "Bomb Threat", sentence: "Threat protocols execute, clear the target building under Signal 73 codes.", layman: "A dangerous call threatening that an explosive package is inside a building" },
    { id: "Signal 74", type: "Signal", desc: "Terrorist Incident", sentence: "Federal interface networks override sector frequencies for a Signal 74 event.", layman: "A severe international scale threat action overriding all local nets" },
    { id: "Signal 75", type: "Signal", desc: "Air Rifle", sentence: "Complainant reports window damaged by a projectile projectile, log Signal 75.", layman: "Property damage caused by a pellet gun weapon line click" },
    { id: "Signal 76", type: "Signal", desc: "Abandoned Children", sentence: "Juveniles found alone inside an empty apartment property, start a Signal 76.", layman: "Young kids left unsupervised inside a vacant structural building floor" },
    { id: "Signal 78", type: "Signal", desc: "Lookout", sentence: "Copy that broadcast, updating dispatch lookup records for a Signal 78 match.", layman: "A formal description alert broadcasted to help units spot a suspect" },
    { id: "Signal 79", type: "Signal", desc: "Stolen Vehicle - In Progress", sentence: "LoJack tracking equipment marks an active moving Signal 79 vehicle target.", layman: "An ongoing theft of an auto happening right now before lines clear" },
    { id: "Signal 80", type: "Signal", desc: "Gas Leak", sentence: "Pungent aromatic pressure signatures track back to a basement Signal 80 fault.", layman: "A gas pipeline burst flooding a basement room with fumes" },
    { id: "Signal 81", type: "Signal", desc: "Street Hazard", sentence: "Debris scattered across middle highway boundaries creates a serious Signal 81.", layman: "Large pieces of trash or objects blocking lanes dangerously" },
    { id: "Signal 81W", type: "Signal", desc: "Weather Hazard", sentence: "Flash floods making low bridges unsafe, activate localized Signal 81W notes.", layman: "Severe local storm weather patterns making roads or pathways unsafe" },
    { id: "Code 5B", type: "Code", desc: "Domestic - Report/Arrest", sentence: "Suspect taken into physical custody on a confirmed Code 5B assault resolution.", layman: "Domestic fight resulting in a physical arrest" },
    { id: "Code 6", type: "Code", desc: "False Alarm", sentence: "Commercial sensor triggered by system tests, log a clear Code 6.", layman: "Security alarm went off by accident, no emergency found" },
    { id: "Code 7", type: "Code", desc: "Available For Service", sentence: "Unit 204 has resolved all prior processing, mark us Code 7 on air.", layman: "Officer is finished with the call and ready for new assignments" },
    { id: "Code 8", type: "Code", desc: "Person Gone", sentence: "Suspect cleared the area before units established a line, tag a Code 8.", layman: "The suspect left the scene before the officers arrived" },
    { id: "Code 9", type: "Code", desc: "Transfer Responsibility", sentence: "Passing structural command blocks to arriving field support, clear Code 9.", layman: "Handing over control of the scene to another officer or team" },
    { id: "Code 10", type: "Code", desc: "Vehicle Impound", sentence: "Towing a vehicle abandoned inside intersection lanes, file a Code 10 log.", layman: "Towing and locking up a vehicle in the police impound lot" },
    { id: "Code 11", type: "Code", desc: "Information", sentence: "Updating database indexes to capture dynamic local Code 11 material.", layman: "General information loop or administrative data note" },
    { id: "Code 12", type: "Code", desc: "No Arrest/Report", sentence: "Field resolution completed cleanly, closing out the card as a Code 12.", layman: "Situation resolved peacefully without any arrest or paperwork filed" }
];
const apdCodesList = [
    { id: "Code 13", type: "Code", desc: "No Valid Address", sentence: "Complainant tracking information cannot be localized, mark as Code 13.", layman: "The address provided does not exist or cannot be found" },
    { id: "Code 14A", type: "Code", desc: "Alarm Refused - Alarm Out", sentence: "Commercial business profile marked under Code 14A status records.", layman: "Business manager refuses to pay or verify an alarm system failure" },
    { id: "Code 14B", type: "Code", desc: "Alarm Refused - Alarm Reset", sentence: "Alarm reset executed during monitoring tracking operations, close as Code 14B.", layman: "The unverified alarm was forced to reset by tracking operators" },
    { id: "Code 15A", type: "Code", desc: "Alarm Owner On Way - Alarm Out", sentence: "Keyholder responding to site location under active Code 15A metrics.", layman: "Store keyholder is traveling to the scene after an alert" }
];

const masterDatabase = [...apdDatabase, ...apdCodes, ...apdDispositions, ...apdFinalSection, ...apdCodesList];
const officerMarathonQuestions = [
    { question: "An emergency tone sounds across the zone. A unit under immediate threat requests backup near downtown. Identify the code.", options: ["Signal 29", "Signal 59", "Signal 63", "Code 21"], matchIndex: 2, layman: "Help request! An officer is trapped and requires immediate team backup assistance.", id: "Signal 63", context: "Peachtree Street" },
    { question: "A perimeter unit initiates an immediate tactical pursuit against a fleeing felony car down I-20. What signal applies?", options: ["Signal 72", "Signal 72P", "Code 3", "Signal 79"], matchIndex: 1, layman: "High-speed chase! Police are actively pursuing a fleeing criminal car down the highway.", id: "Signal 72P", context: "Interstate 20 Westbound" },
    { question: "Units respond Code 3 to an ongoing armed hijacking of a commercial vehicle. What signal classifies this active event?", options: ["Signal 35C", "Signal 44C", "Signal 36B", "Signal 21"], matchIndex: 0, layman: "Carjacking in progress! A thief is stealing a car by gunpoint or physical force right now.", id: "Signal 35C", context: "Moreland Avenue" },
    { question: "Dispatch transmits an alert regarding an armed individual carrying an unholstered rifle near a transit station. What signal applies?", options: ["Signal 54", "Signal 69", "Signal 78", "Code 25"], matchIndex: 1, layman: "Armed person! An individual is walking near a public space carrying a weapon out in the open.", id: "Signal 69", context: "MARTA Station Zone" },
    { question: "A priority dispatch logs an active armed robbery inside a retail storefront right now. Identify the signal.", options: ["Signal 44B", "Signal 36B", "Signal 36P", "Code 5B"], matchIndex: 1, layman: "Store hold-up in progress! An armed suspect is robbing a business right this second.", id: "Signal 36B", context: "Buckhead Shopping Plaza" }
];
const secondQuestionsSet = [
    { question: "A suspect violently rips a purse away from a pedestrian on a public pathway and runs. What signal describes this event?", options: ["Signal 45", "Signal 77", "Signal 44P", "Signal 36P"], matchIndex: 1, layman: "Snatch theft robbery! A criminal just ripped property away from a walking citizen and fled.", id: "Signal 77", context: "Piedmont Park Trail" },
    { question: "A residential call involving a dynamic family physical altercation is reported to dispatch. Identify the signal.", options: ["Signal 29", "Signal 58", "Signal 23", "Code 5A"], matchIndex: 1, layman: "Domestic fight! Family structures are fighting violently inside a residential house block.", id: "Signal 58", context: "Cascade Road Residence" },
    { question: "Units handle a dynamic traffic stop and discover an active felony arrest warrant on the operator during verification. What disposition code is used?", options: ["Code 23", "Code 28A", "Code 28B", "Code 17"], matchIndex: 1, layman: "Wanted check hit! Computer lookups show this driver has a valid arrest warrant pending.", id: "Code 28A", context: "Northside Drive Junction" },
    { question: "A supervisor requests an emergency assignment execution utilizing full assets (Emergency lights and sound siren arrays). What response mode applies?", options: ["Code 1", "Code 2", "Code 3", "Code 7"], matchIndex: 2, layman: "Maximum response mode! Rush to the crime scene immediately using flashing lights and emergency sirens.", id: "Code 3", context: "Metropolitan Area Patrol" },
    { question: "A major collision is verified on the highway where a split fuel line has caused the vehicle engine to fully ignite. What signal is logged?", options: ["Signal 34", "Signal 41F", "Signal 41IT", "Signal 30"], matchIndex: 1, layman: "Car crash fire! A vehicle accident impact split open gas components and burst into large flames.", id: "Signal 41F", context: "Connector Core Lanes" }
];
const thirdQuestionsSet = [
    { question: "Bomb detection squads locate an active improvised explosive artifact package under a municipal bridge. Identify the code profile.", options: ["Signal 73P", "Code 25", "Signal 73", "Code 30"], matchIndex: 1, layman: "Bomb found! Threat investigators discovered a confirmed explosive device layout left at a site.", id: "Code 25", context: "Bankhead Bridge Support" },
    { question: "An emergency unit drops off the radio grid mid-call, and tracking operators verify a dynamic 911 drop loop. What signal tracks this?", options: ["Signal 16", "Signal 39", "Signal 55", "Code 22"], matchIndex: 2, layman: "Dropped emergency call line! A 911 call line disconnected instantly before details could be verified.", id: "Signal 55", context: "Zone 3 Boundary Grid" },
    { question: "A field unit deploys an oleoresin capsicum (pepper spray) canister to handle a combative, non-compliant subject. What code must be recorded?", options: ["Code 20", "Code 23", "Code 31", "Signal 47"], matchIndex: 0, layman: "Chemical control tool deployment! An officer used pepper spray on a fighting suspect.", id: "Code 20", context: "Peachtree Street Corridor" },
    { question: "Detectives complete an on-scene investigation where stolen goods are recovered and safely handed back to the citizen. What code applies?", options: ["Code 16", "Code 19", "Code 12", "Signal 52"], matchIndex: 0, layman: "Stolen property return! Returning recovered stolen items cleanly back to their original owner.", id: "Code 16", context: "Precinct Property Desk" },
    { question: "A patrol officer locates an empty vehicle on an access shoulder that has been stripped and left abandoned. What code handles this?", options: ["Signal 1", "Signal 1R", "Signal 37", "Code 10"], matchIndex: 0, layman: "Deserted junk vehicle! An empty car has been left dumped on the public roadside permanently.", id: "Signal 1", context: "Martin Luther King Jr Dr" },
    { question: "A specialized call is dispatched regarding a suspect looking through structural blinds into a private residential space. Identify the signal.", options: ["Signal 54", "Signal 70", "Signal 66", "Signal 71"], matchIndex: 2, layman: "Peeping tom prowler! Someone is spying on citizens illegally through their private home window glass panes.", id: "Signal 66", context: "West End Community Block" },
    { question: "An alarm company triggers tracking lines for a hidden, non-sounding monitoring breach layout inside a jewelry vault. What signal tracks this?", options: ["Signal 2A", "Signal 2S", "Signal 6B", "Code 14A"], matchIndex: 1, layman: "Silent break-in alarm! A hidden commercial security sensor tripped without making any sound.", id: "Signal 2S", context: "Downtown Financial Sector" },
    { question: "A vehicle collision occurs on an arterial road resulting in multiple passengers pinned inside the compressed wreckage. What signal applies?", options: ["Signal 41I", "Signal 41IT", "Signal 87", "Signal 92"], matchIndex: 1, layman: "Trapped in crash! Wreckage compressed on impact, trapping passengers tightly inside.", id: "Signal 41IT", context: "Piedmont Road Core Route" },
    { question: "A home invasion is called in by a resident hiding inside a closet while suspects break through a window. What signal applies?", options: ["Signal 6R", "Signal 42R", "Signal 36R", "Signal 44R"], matchIndex: 2, layman: "Active break-in with occupants! Armed robbers forced their way inside a house while residents were home.", id: "Signal 36R", context: "Donald Lee Hollowell Pkwy" },
    { question: "Command lines order all units on Sector 2 to immediately transition communication strings over to a tactical backup channel. What signal is used?", options: ["Signal 39", "Signal 62", "Signal 67", "Code 9"], matchIndex: 1, layman: "Change radio channels! All responding police units switch their radios to a backup channel now.", id: "Signal 62", context: "Zone 1 Dispatch Channel" }
];

officerMarathonQuestions.push(...secondQuestionsSet, ...thirdQuestionsSet);
